version: '3'
services:
  gologin-1:
    build: ./gologin
    ports:
      - "5901:5900"
    shm_size: "1024m"
    networks:
      - gologin-network
  gologin-2:
    build: ./gologin
    ports:
      - "5902:5900"
    shm_size: "1024m"
    networks:
      - gologin-network
  gologin-3:
    build: ./gologin
    ports:
      - "5903:5900"
    shm_size: "1024m"
    networks:
      - gologin-network
  # vnc:
  #   build: ./vnc
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DOCKER_SOCKET=/var/run/docker.sock
  #   volumes:
  #     # Linux / Mac
  #     # - /var/run/docker.sock:/var/run/docker.sock
  #     # Windows
  #     - //var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - gologin-network
networks:
  gologin-network:
    driver: bridge