export default {
  "audioContext": {
    "enable": true,
    "noiseValue": 1.261387321711
  },
  "canvasMode": "noise",
  "canvasNoise": 0.99409813,
  "client_rects_noise_enable": true,
  "deviceMemory": 8192,
  "dns": "",
  "doNotTrack": null,
  "geoLocation": {
    "accuracy": 100,
    "latitude": 32.9473,
    "longitude": -96.7028,
    "mode": "prompt"
  },
  "getClientRectsNoice": 7.1653,
  "get_client_rects_noise": 7.1653,
  "hardwareConcurrency": 4,
  "is_m1": false,
  "langHeader": "en-US,en-GB;q=0.9,en;q=0.8",
  "languages": "en-US,en-GB,en",
  "mediaDevices": {
    "audioInputs": 1,
    "audioOutputs": 1,
    "enable": true,
    "uid": "9548905da98f467cb7c271d1c463f06cdf426d1c8a364e088c7ad3bb6e",
    "videoInputs": 0
  },
  "mobile": {
    "device_scale_factor": 1.00000001,
    "enable": false,
    "height": 768,
    "width": 1366
  },
  "name": "MAC",
  "navigator": {
    "max_touch_points": 0,
    "platform": "MacIntel"
  },
  "plugins": {
    "all_enable": true,
    "flash_enable": true
  },
  "proxy": {
    "password": "zorovhs",
    "username": "Maika2506"
  },
  "screenHeight": 1080,
  "screenWidth": 1820,
  "startupUrl": "",
  "startup_urls": [
    ""
  ],
  "storage": {
    "enable": true
  },
  "timezone": {
    "id": "Asia/Saigon"
  },
  "unpinable_extension_names": ["passwords-ext"],
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15",
  "webGl": {
    "mode": true,
    "renderer": "ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics OpenGL Engine (1x6x8 (fused) LP, OpenGL 4.1 INTEL-16.4.5)",
    "vendor": "Google Inc. (Intel Inc.)"
  },
  "webRtc": {
    "fill_based_on_ip": true,
    "localIps": "",
    "local_ip_masking": false,
    "mode": "public",
    "publicIP": "45.79.46.127",
    "public_ip": "45.79.46.127"
  },
  "webgl": {
    "metadata": {
      "mode": true,
      "renderer": "ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics OpenGL Engine (1x6x8 (fused) LP, OpenGL 4.1 INTEL-16.4.5)",
      "vendor": "Google Inc. (Intel Inc.)"
    }
  },
  "webglNoiceEnable": true,
  "webglNoiseValue": 7.643,
  "webglParams": {
    "antialiasing": true,
    "extensions": ["EXT_color_buffer_float", "EXT_color_buffer_half_float", "EXT_disjoint_timer_query_webgl2", "EXT_float_blend", "EXT_texture_compression_bptc", "EXT_texture_compression_rgtc", "EXT_texture_filter_anisotropic", "EXT_texture_norm16", "KHR_parallel_shader_compile", "OES_draw_buffers_indexed", "OES_texture_float_linear", "OVR_multiview2", "WEBGL_compressed_texture_s3tc", "WEBGL_compressed_texture_s3tc_srgb", "WEBGL_debug_renderer_info", "WEBGL_debug_shaders", "WEBGL_lose_context", "WEBGL_multi_draw"],
    "glCanvas": "webgl2",
    "glParamValues": [{
      "name": "ALIASED_LINE_WIDTH_RANGE",
      "value": {
        "0": 1,
        "1": 1
      }
    }, {
      "name": "ALIASED_POINT_SIZE_RANGE",
      "value": {
        "0": 1,
        "1": 1024
      }
    }, {
      "name": ["DEPTH_BITS", "STENCIL_BITS"],
      "value": "n/a"
    }, {
      "name": "MAX_3D_TEXTURE_SIZE",
      "value": 2048
    }, {
      "name": "MAX_ARRAY_TEXTURE_LAYERS",
      "value": 2048
    }, {
      "name": "MAX_COLOR_ATTACHMENTS",
      "value": 8
    }, {
      "name": "MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS",
      "value": 200704
    }, {
      "name": "MAX_COMBINED_TEXTURE_IMAGE_UNITS",
      "value": 32
    }, {
      "name": "MAX_COMBINED_UNIFORM_BLOCKS",
      "value": 24
    }, {
      "name": "MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS",
      "value": 212992
    }, {
      "name": "MAX_CUBE_MAP_TEXTURE_SIZE",
      "value": 16384
    }, {
      "name": "MAX_DRAW_BUFFERS",
      "value": 8
    }, {
      "name": "MAX_FRAGMENT_INPUT_COMPONENTS",
      "value": 120
    }, {
      "name": "MAX_FRAGMENT_UNIFORM_BLOCKS",
      "value": 12
    }, {
      "name": "MAX_FRAGMENT_UNIFORM_COMPONENTS",
      "value": 4096
    }, {
      "name": "MAX_FRAGMENT_UNIFORM_VECTORS",
      "value": 1024
    }, {
      "name": "MAX_PROGRAM_TEXEL_OFFSET",
      "value": 7
    }, {
      "name": "MAX_RENDERBUFFER_SIZE",
      "value": 16384
    }, {
      "name": "MAX_SAMPLES",
      "value": 16
    }, {
      "name": "MAX_TEXTURE_IMAGE_UNITS",
      "value": 16
    }, {
      "name": "MAX_TEXTURE_LOD_BIAS",
      "value": 2
    }, {
      "name": "MAX_TEXTURE_SIZE",
      "value": 16384
    }, {
      "name": "MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS",
      "value": 120
    }, {
      "name": "MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS",
      "value": 4
    }, {
      "name": "MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS",
      "value": 4
    }, {
      "name": "MAX_UNIFORM_BLOCK_SIZE",
      "value": 65536
    }, {
      "name": "MAX_UNIFORM_BUFFER_BINDINGS",
      "value": 24
    }, {
      "name": "MAX_VARYING_COMPONENTS",
      "value": 120
    }, {
      "name": "MAX_VARYING_VECTORS",
      "value": 30
    }, {
      "name": "MAX_VERTEX_ATTRIBS",
      "value": 16
    }, {
      "name": "MAX_VERTEX_OUTPUT_COMPONENTS",
      "value": 120
    }, {
      "name": "MAX_VERTEX_TEXTURE_IMAGE_UNITS",
      "value": 16
    }, {
      "name": "MAX_VERTEX_UNIFORM_BLOCKS",
      "value": 12
    }, {
      "name": "MAX_VERTEX_UNIFORM_COMPONENTS",
      "value": 16384
    }, {
      "name": "MAX_VERTEX_UNIFORM_VECTORS",
      "value": 4096
    }, {
      "name": "MAX_VIEWPORT_DIMS",
      "value": {
        "0": 32767,
        "1": 32767
      }
    }, {
      "name": "MIN_PROGRAM_TEXEL_OFFSET",
      "value": -8
    }, {
      "name": ["RED_BITS", "GREEN_BITS", "BLUE_BITS", "ALPHA_BITS"],
      "value": "n/a"
    }, {
      "name": "RENDERER",
      "value": "WebKit WebGL"
    }, {
      "name": "SHADING_LANGUAGE_VERSION",
      "value": "WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)"
    }, {
      "name": "UNIFORM_BUFFER_OFFSET_ALIGNMENT",
      "value": 256
    }, {
      "name": "VENDOR",
      "value": "WebKit"
    }, {
      "name": "VERSION",
      "value": "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
    }],
    "shaiderPrecisionFormat": "highp/highp",
    "supportedFunctions": [{
      "name": "beginQuery",
      "supported": true
    }, {
      "name": "beginTransformFeedback",
      "supported": true
    }, {
      "name": "bindBufferBase",
      "supported": true
    }, {
      "name": "bindBufferRange",
      "supported": true
    }, {
      "name": "bindSampler",
      "supported": true
    }, {
      "name": "bindTransformFeedback",
      "supported": true
    }, {
      "name": "bindVertexArray",
      "supported": true
    }, {
      "name": "blitFramebuffer",
      "supported": true
    }, {
      "name": "clearBufferfi",
      "supported": true
    }, {
      "name": "clearBufferfv",
      "supported": true
    }, {
      "name": "clearBufferiv",
      "supported": true
    }, {
      "name": "clearBufferuiv",
      "supported": true
    }, {
      "name": "clientWaitSync",
      "supported": true
    }, {
      "name": "compressedTexImage3D",
      "supported": true
    }, {
      "name": "compressedTexSubImage3D",
      "supported": true
    }, {
      "name": "copyBufferSubData",
      "supported": true
    }, {
      "name": "copyTexSubImage3D",
      "supported": true
    }, {
      "name": "createQuery",
      "supported": true
    }, {
      "name": "createSampler",
      "supported": true
    }, {
      "name": "createTransformFeedback",
      "supported": true
    }, {
      "name": "createVertexArray",
      "supported": true
    }, {
      "name": "deleteQuery",
      "supported": true
    }, {
      "name": "deleteSampler",
      "supported": true
    }, {
      "name": "deleteSync",
      "supported": true
    }, {
      "name": "deleteTransformFeedback",
      "supported": true
    }, {
      "name": "deleteVertexArray",
      "supported": true
    }, {
      "name": "drawArraysInstanced",
      "supported": true
    }, {
      "name": "drawBuffers",
      "supported": true
    }, {
      "name": "drawElementsInstanced",
      "supported": true
    }, {
      "name": "drawRangeElements",
      "supported": true
    }, {
      "name": "endQuery",
      "supported": true
    }, {
      "name": "endTransformFeedback",
      "supported": true
    }, {
      "name": "fenceSync",
      "supported": true
    }, {
      "name": "framebufferTextureLayer",
      "supported": true
    }, {
      "name": "getActiveUniformBlockName",
      "supported": true
    }, {
      "name": "getActiveUniformBlockParameter",
      "supported": true
    }, {
      "name": "getActiveUniforms",
      "supported": true
    }, {
      "name": "getBufferSubData",
      "supported": true
    }, {
      "name": "getFragDataLocation",
      "supported": true
    }, {
      "name": "getIndexedParameter",
      "supported": true
    }, {
      "name": "getInternalformatParameter",
      "supported": true
    }, {
      "name": "getQuery",
      "supported": true
    }, {
      "name": "getQueryParameter",
      "supported": true
    }, {
      "name": "getSamplerParameter",
      "supported": true
    }, {
      "name": "getSyncParameter",
      "supported": true
    }, {
      "name": "getTransformFeedbackVarying",
      "supported": true
    }, {
      "name": "getUniformBlockIndex",
      "supported": true
    }, {
      "name": "getUniformIndices",
      "supported": true
    }, {
      "name": "invalidateFramebuffer",
      "supported": true
    }, {
      "name": "invalidateSubFramebuffer",
      "supported": true
    }, {
      "name": "isQuery",
      "supported": true
    }, {
      "name": "isSampler",
      "supported": true
    }, {
      "name": "isSync",
      "supported": true
    }, {
      "name": "isTransformFeedback",
      "supported": true
    }, {
      "name": "isVertexArray",
      "supported": true
    }, {
      "name": "pauseTransformFeedback",
      "supported": true
    }, {
      "name": "readBuffer",
      "supported": true
    }, {
      "name": "renderbufferStorageMultisample",
      "supported": true
    }, {
      "name": "resumeTransformFeedback",
      "supported": true
    }, {
      "name": "samplerParameterf",
      "supported": true
    }, {
      "name": "samplerParameteri",
      "supported": true
    }, {
      "name": "texImage3D",
      "supported": true
    }, {
      "name": "texStorage2D",
      "supported": true
    }, {
      "name": "texStorage3D",
      "supported": true
    }, {
      "name": "texSubImage3D",
      "supported": true
    }, {
      "name": "transformFeedbackVaryings",
      "supported": true
    }, {
      "name": "uniform1ui",
      "supported": true
    }, {
      "name": "uniform1uiv",
      "supported": true
    }, {
      "name": "uniform2ui",
      "supported": true
    }, {
      "name": "uniform2uiv",
      "supported": true
    }, {
      "name": "uniform3ui",
      "supported": true
    }, {
      "name": "uniform3uiv",
      "supported": true
    }, {
      "name": "uniform4ui",
      "supported": true
    }, {
      "name": "uniform4uiv",
      "supported": true
    }, {
      "name": "uniformBlockBinding",
      "supported": true
    }, {
      "name": "uniformMatrix2x3fv",
      "supported": true
    }, {
      "name": "uniformMatrix2x4fv",
      "supported": true
    }, {
      "name": "uniformMatrix3x2fv",
      "supported": true
    }, {
      "name": "uniformMatrix3x4fv",
      "supported": true
    }, {
      "name": "uniformMatrix4x2fv",
      "supported": true
    }, {
      "name": "uniformMatrix4x3fv",
      "supported": true
    }, {
      "name": "vertexAttribDivisor",
      "supported": true
    }, {
      "name": "vertexAttribI4i",
      "supported": true
    }, {
      "name": "vertexAttribI4iv",
      "supported": true
    }, {
      "name": "vertexAttribI4ui",
      "supported": true
    }, {
      "name": "vertexAttribI4uiv",
      "supported": true
    }, {
      "name": "vertexAttribIPointer",
      "supported": true
    }, {
      "name": "waitSync",
      "supported": true
    }],
    "textureMaxAnisotropyExt": 16
  },
  "webgl_noice_enable": true,
  "webgl_noise_enable": true,
  "webgl_noise_value": 7.643
}